# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orchestrator_pb2 as orchestrator__pb2


class OrchestratorServiceStub(object):
    """-----------------------------------------------------------------------------
    Orchestrator Service API
    -----------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DispatchInference = channel.unary_stream(
                '/orchestrator.OrchestratorService/DispatchInference',
                request_serializer=orchestrator__pb2.InferenceRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.EncryptedToken.FromString,
                )
        self.PerformRAG = channel.unary_unary(
                '/orchestrator.OrchestratorService/PerformRAG',
                request_serializer=orchestrator__pb2.RAGRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.RAGResponse.FromString,
                )


class OrchestratorServiceServicer(object):
    """-----------------------------------------------------------------------------
    Orchestrator Service API
    -----------------------------------------------------------------------------
    """

    def DispatchInference(self, request, context):
        """Main inference API — produces a streaming response of encrypted tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformRAG(self, request, context):
        """Optional RAG subsystem (Orchestrator → Vector Service wrapper).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DispatchInference': grpc.unary_stream_rpc_method_handler(
                    servicer.DispatchInference,
                    request_deserializer=orchestrator__pb2.InferenceRequest.FromString,
                    response_serializer=orchestrator__pb2.EncryptedToken.SerializeToString,
            ),
            'PerformRAG': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformRAG,
                    request_deserializer=orchestrator__pb2.RAGRequest.FromString,
                    response_serializer=orchestrator__pb2.RAGResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """-----------------------------------------------------------------------------
    Orchestrator Service API
    -----------------------------------------------------------------------------
    """

    @staticmethod
    def DispatchInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orchestrator.OrchestratorService/DispatchInference',
            orchestrator__pb2.InferenceRequest.SerializeToString,
            orchestrator__pb2.EncryptedToken.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformRAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.OrchestratorService/PerformRAG',
            orchestrator__pb2.RAGRequest.SerializeToString,
            orchestrator__pb2.RAGResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
