# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orchestrator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"\x88\x01\n\x10InferenceRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x15\n\rclient_pubkey\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\x12\x18\n\x10\x65ncrypted_prompt\x18\x06 \x01(\x0c\")\n\x0e\x45ncryptedToken\x12\x17\n\x0f\x65ncrypted_token\x18\x01 \x01(\x0c\"0\n\nRAGRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"\"\n\x0bRAGResponse\x12\x13\n\x0brag_context\x18\x01 \x01(\t2\xad\x01\n\x13OrchestratorService\x12S\n\x11\x44ispatchInference\x12\x1e.orchestrator.InferenceRequest\x1a\x1c.orchestrator.EncryptedToken0\x01\x12\x41\n\nPerformRAG\x12\x18.orchestrator.RAGRequest\x1a\x19.orchestrator.RAGResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERENCEREQUEST']._serialized_start=37
  _globals['_INFERENCEREQUEST']._serialized_end=173
  _globals['_ENCRYPTEDTOKEN']._serialized_start=175
  _globals['_ENCRYPTEDTOKEN']._serialized_end=216
  _globals['_RAGREQUEST']._serialized_start=218
  _globals['_RAGREQUEST']._serialized_end=266
  _globals['_RAGRESPONSE']._serialized_start=268
  _globals['_RAGRESPONSE']._serialized_end=302
  _globals['_ORCHESTRATORSERVICE']._serialized_start=305
  _globals['_ORCHESTRATORSERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
