# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\">\n\x10\x45ncryptedPayload\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncrypted_blob\x18\x02 \x01(\x0c\")\n\x0e\x45ncryptedToken\x12\x17\n\x0f\x65ncrypted_token\x18\x01 \x01(\x0c\x32S\n\rWorkerService\x12\x42\n\x0cRunInference\x12\x18.worker.EncryptedPayload\x1a\x16.worker.EncryptedToken0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENCRYPTEDPAYLOAD']._serialized_start=24
  _globals['_ENCRYPTEDPAYLOAD']._serialized_end=86
  _globals['_ENCRYPTEDTOKEN']._serialized_start=88
  _globals['_ENCRYPTEDTOKEN']._serialized_end=129
  _globals['_WORKERSERVICE']._serialized_start=131
  _globals['_WORKERSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
